### ISSUE TITLE
Eclipse unexpected behavior

### ISSUE THREAD

**Issue by masoodahm** [ceylon/ceylon-ide-eclipse#1606] opened 2015-11-09 07:41 UTC
hi, I get an exception "`The ExpressionVisitor caused an exception visiting a InvocationExpression node: "com.redhat.ceylon.model.loader.ModelResolutionException: JDT reference binding without a JDT IType element : com.google.common.cache.Cache" at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toType(JDTModelLoader.java:1148)`"

when I try to run my code in eclipse, but it compiles and runs fine from the linux terminal.
I was trying to use a java html templating engine in ceylon when this happened.

To reproduce the issue, my code is below.
module.ceylon file
```ceylon
native("jvm") module cryna "1.0.0" {
	import ceylon.net "1.2.0";
	import "com.mitchellbosecke:pebble" "1.6.0";
	import java.base "8";
}
```

package.ceylon
```ceylon
shared package cryna;
```

and finally run.ceylon
```ceylon
import ceylon.net.http.server {
    newServer,
	Endpoint,
	startsWith
}

import java.io {
    StringWriter
}
import com.mitchellbosecke.pebble {
    PebbleEngine
}
import com.mitchellbosecke.pebble.loader {
    FileLoader
}
import com.mitchellbosecke.pebble.template {
    PebbleTemplate
}

shared void run() => newServer {
    Endpoint {
	path = startsWith("/");
	(req, res) {
	    variable StringWriter wr = StringWriter();
	    FileLoader fl = FileLoader();
	    PebbleEngine engine = PebbleEngine(fl);
	    PebbleTemplate compiledTemplate = engine.getTemplate("/home/masood/Documents/misc/experimental/templates/home.html");

	    compiledTemplate.evaluate(wr);
	    
	    return res.writeString(wr.string);
	};
    }
}.start();
```
you can put any regular html page in the engine.getTemplate

**Comment by gavinking** [comment] 2015-11-09 07:53
@masoodahm thanks for reporting this.

**Comment by davidfestal** [comment] 2015-12-10 17:25
It appears that this error comes from the google guava dependency not being shared. A typical maven interop problem that appears when maven dependencies in which some classes are transitively visible are not exported.
Using the following `overrides.xml` file: 
```xml
<overrides xmlns="http://www.ceylon-lang.org/xsd/overrides">
	<artifact groupId="com.mitchellbosecke" artifactId="pebble">
		<share groupId="com.google.guava" artifactId="guava"/>
	</artifact>
</overrides>
``` 
Fixes the problem.

The real question is : why would this produce such an exception. However, the message of the root cause exception is quite clear about the fact that the `Cache` class (known to be in the guava module) is probably not found. Then the Ceylon Module Dependency view confirmed this.

@masoodahm : so your problem is fixed by the given `overrides.xml` file, but I keep this issue opened to try fixing the unclear error message.

**Closed** 2015-12-14 11:00 UTC
Labels: bug on last release, high priority
