### ISSUE TITLE
stack trace at startup

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1334] opened 2015-04-26 22:26 UTC
I started seeing this:

```
MavenArtifactInfo class : org.jboss.shrinkwrap.resolver.impl.maven.MavenArtifactInfoImpl loaded from : file:/Applications/eclipse 2/plugins/com.redhat.ceylon.maven-support_2.0.0/
java.lang.NoSuchMethodError: org.jboss.shrinkwrap.resolver.api.maven.MavenArtifactInfo.isOptional()Z
	at com.redhat.ceylon.cmr.maven.AetherUtils.fetchDependencies(AetherUtils.java:243)
	at com.redhat.ceylon.cmr.maven.AetherUtils.findDependencies(AetherUtils.java:176)
	at com.redhat.ceylon.cmr.maven.AetherUtils.findDependencies(AetherUtils.java:142)
	at com.redhat.ceylon.cmr.maven.AetherRepository.getArtifactResultInternal(AetherRepository.java:95)
	at com.redhat.ceylon.cmr.impl.AbstractRepository.getArtifactResult(AbstractRepository.java:125)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.toArtifactResult(AbstractNodeRepositoryManager.java:117)
	at com.redhat.ceylon.cmr.impl.RootRepositoryManager.getArtifactResult(RootRepositoryManager.java:111)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getArtifactResult(AbstractNodeRepositoryManager.java:181)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:197)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:225)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:87)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2222)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:1)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:249)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.parseCeylonModel(CeylonBuilder.java:2065)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonProjectModulesContainer.resolveClasspath(CeylonProjectModulesContainer.java:309)
	at com.redhat.ceylon.eclipse.core.classpath.InitDependenciesJob.run(InitDependenciesJob.java:51)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by gavinking** [comment] 2015-05-08 10:16
Folks WTF is up with this one!?

There's something wrong with the shrinkwrap version someone is using.

**Comment by davidfestal** [comment] 2015-06-09 13:20
I don't get this one anymore. I was able to step-over the `isOptional()` call without any error. 
@quintesse, @FroMage, @alesj : Did anyone touch or update some jars so that it is fixed ?

**Comment by quintesse** [comment] 2015-06-09 17:31
Not me and I think that `isOptional()` has been there for quite some time already. I never saw this error btw.

**Comment by davidfestal** [comment] 2015-06-30 20:39
closing since we cannot reproduce it anymore.
Please reopen it if any one encounter the problem again

**Closed by davidfestal** 2015-06-30 20:39 UTC
Labels: bug, COULD_NOT_REPRODUCE_ANYMORE, WAITING_FOR_ANSWER
