### ISSUE TITLE
Run configuration for tests are not updated with new tests

### ISSUE THREAD

**Issue by PhiLhoSoft** [ceylon/ceylon-ide-eclipse#1109] opened 2014-08-28 16:08 UTC
I saw practice to write Ceylon tests as a series of top-level functions annotated with test.
It is nice (simpler than classical JUnit structure) but it leads to an unexpected problem: when I add a new test, and run again the test, via the Rerun Test button in the Ceylon Test view, or via the Run button of the main toolbar: the new test is happily skipped, leading to a blissful evergreen state...

I suppose the run configuration that is created when we do Run As > Ceylon Test takes a snapshot of the top-level items and runs only them, without updating them with the current state of the editor.
If we run the tests again with Run As > Ceylon Test, it will create a new run configuration, polluting the run space...

A workaround is to wrap the test methods in a class (the methods must be shared, then), which might be the best practice after all, as it allows to have same test method names in different files in the same package... And it allows to scope objects common to several tests.

I don't know if this behavior can be fixed (it can depend on Eclipse itself), but I leave this bug as reference for those stumbling on the same issue.

**Comment by thradec** [comment] 2015-02-26 12:39
Closing, not a bug.

**Closed by thradec** 2015-02-26 12:39 UTC
Labels: bug
