### ISSUE TITLE
Typechecker errors are removed when using native("js")

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1497] opened 2015-09-19 18:29 UTC
I created a new project, enabled both "Compile for JVM" and "Compile for Javascript", then created two modules:

- one is annotated `native("js")`
- one is annotated `native("jvm")`

In the JS module, typechecker errors are not reported. This leads to the JS backend being invoked, and the compilation succeeds: I can run my code in the browser although the Ceylon code is incorrect. This only happens in the IDE.

Example of invalid code, for which no typechecker error is reported:

```
void fun(dynamic foo, Lololol lol) { // note the invalid type Lololol
    print(foo); // this shouldn't work because foo is dynamic
}
```

**Comment by gavinking** [comment] 2015-09-19 18:33
To be clear, the critical part of this is that when you annotate a module `native("js")`, some typechecker errors never get reported.

It is _not_ necessary to (a) enable the JVM compiler, nor (b) have a second `native("jvm")` module to observe this. The problem is completely in the JS side.

**Comment by gavinking** [comment] 2015-09-19 18:33
@quintesse this is for you.

**Comment by quintesse** [comment] 2015-10-06 12:57
And #1515 seems to have fixed this one too. Yay! Closing.

**Closed by quintesse** 2015-10-06 12:57 UTC
Labels: bug, high priority
