### ISSUE TITLE
Module depency breaks module renaming

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-ide-eclipse#1254] opened 2015-02-15 16:33 UTC
Create a projet with two modules `foo` and `bar` with the following descriptors
```ceylon
module foo "1.0.0" {}
```
and
```ceylon
module bar "1.0.0" {
    import foo "1.0.0";
}
```
try to rename module `foo` (Alt+Shit+R), choose a new name click `OK` you get a dialog box with 
```
An unexpected exception occurred while performing the refactoring. See the log for more details. -1
```
and in the logs
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.eclipse.jdt.internal.core.search.matching.PackageReferenceLocator.matchReportImportRef(PackageReferenceLocator.java:182)
	at org.eclipse.jdt.internal.core.search.matching.PatternLocator.matchLevelAndReportImportRef(PatternLocator.java:370)
	at org.eclipse.jdt.internal.core.search.matching.PackageReferenceLocator.matchLevelAndReportImportRef(PackageReferenceLocator.java:163)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2421)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:1733)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1143)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1184)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1316)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:95)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:231)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:515)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:584)
	at org.eclipse.jdt.internal.corext.refactoring.RefactoringSearchEngine.internalSearch(RefactoringSearchEngine.java:143)
	at org.eclipse.jdt.internal.corext.refactoring.RefactoringSearchEngine.search(RefactoringSearchEngine.java:130)
	at org.eclipse.jdt.internal.corext.refactoring.rename.RenamePackageProcessor$PackageRenamer.getReferences(RenamePackageProcessor.java:736)
	at org.eclipse.jdt.internal.corext.refactoring.rename.RenamePackageProcessor$PackageRenamer.doRename(RenamePackageProcessor.java:708)
	at org.eclipse.jdt.internal.corext.refactoring.rename.RenamePackageProcessor.doCheckFinalConditions(RenamePackageProcessor.java:421)
	at org.eclipse.jdt.internal.corext.refactoring.rename.JavaRenameProcessor.checkFinalConditions(JavaRenameProcessor.java:48)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:224)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:85)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:121)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:209)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2345)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:87)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
```

**Comment by gavinking** [comment] 2015-02-15 18:14
Grrrrr. Eclipse's infrastructure for this is amazingly badly-designed and fragile. :-/

**Comment by gavinking** [comment] 2015-02-15 20:30
So I have investigated this one a bit, and it does not seem to be the fault of my `RenameParticipant`, which, in fact, never seems to actually get called. Nor is it the fault of the Ceylon Explorer, since the same error occurs when renaming the package in the JDT Package Explorer.

However, I can make the error disappear by checking 'Disable Java classes calling Ceylon' in 'Ceylon Configuration'. It seems to me that the generated class files in the `classes` folder are not being marked as derived resources, so for some reason the Java refactoring stuff is searching in the binary `.class` files  for references. (To me this is more of a bug in JDT that in our plugin.)

**Comment by gavinking** [comment] 2015-02-15 20:38
I confirm that even though the `.exploded` folder itself is marked as derived, the actual class files are not.

**Comment by gavinking** [comment] 2015-02-15 20:41
Hrm. Manually marking them as derived does not seem to help. Grr. How else can I make JDT ignore them?

**Comment by gavinking** [comment] 2015-02-15 22:40
So, digging further, I'm inclined to think that the problem might be caused by as not generating correct line number information for `import` statements in module descriptors. @tombentley @davidfestal WDYT?

**Comment by gavinking** [comment] 2015-03-12 16:37
Just so you guys realize, I essentially gave up on this issue. The problem seems to be somewhere deep in Eclipse where it starts looking in Ceylon `.class` files in the `.exploded` folder and apparently finds something it just doesn't know how to handle. I don't know why it even looks in the `.exploded` folder or how to stop it from doing that.

**Comment by davidfestal** [comment] 2015-03-12 16:41
I'll try to have a look.

**Closed** 2015-03-16 13:26 UTC
Labels: bug, IN PROGRESS
