### ISSUE TITLE
errors shown in outline of StringBuilder

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1531] opened 2015-10-13 10:25 UTC
When I open `ceylon.language::StringBuilder` in the IDE, I see lots of errors in the outline. This is a regression. @davidfestal how did you fix this last time?

**Comment by davidfestal** [comment] 2015-10-14 20:08
That might be related to a change in the way natives are managed, which brings an error during the source-based typechecking that occurs inside the Editor.
This is a *very* sensible part, since having both an editor-local source-based model coexisting with the central binary-based model is a need that is fully specific to the IDE. Accommodating this IDE-specific use-case with the native support already took me many efforts. But this might be broken again due to the recent changes to the natives I assume.

**Comment by davidfestal** [comment] 2015-10-15 13:03
Waiting for ceylon/ceylon-compiler#2356 : this should fix the problem according to what I've seen.

**Comment by davidfestal** [comment] 2015-10-16 09:32
I don't get it, but didn't pull the very last master since yesterday. So this might come from something. I assume this is not related to my changes that don't impact the model loader at all,  but only UI-related things (navigation, etc ...)

**Comment by davidfestal** [comment] 2015-10-16 11:42
@gavinking :  Is there anything specialyou think I could do to reproduce your compilation error ?

**Comment by gavinking** [comment] 2015-10-16 11:50
No: just open `StringBuilder` from `ceylon.language` and look at the outline.

**Comment by davidfestal** [comment] 2015-10-16 12:00
@gavinking : oops my 2 last messages were for issue #1518 that you already closed !

**Comment by davidfestal** [comment] 2015-10-28 16:51
This works correctly now. Closing.

**Closed by davidfestal** 2015-10-28 16:51 UTC
Labels: bug, IN PROGRESS, WAITING_FOR_ANSWER
