### ISSUE TITLE
NPE in outline label retrieval

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1115] opened 2014-09-03 13:27 UTC
```
Caused by: java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.util.Nodes.findNode(Nodes.java:178)
	at com.redhat.ceylon.eclipse.util.Nodes.findNode(Nodes.java:173)
	at com.redhat.ceylon.eclipse.code.outline.CeylonOutlineNode.getLabel(CeylonOutlineNode.java:190)
	at com.redhat.ceylon.eclipse.code.outline.CeylonDocumentRangeNode.getName(CeylonDocumentRangeNode.java:41)
	at org.eclipse.compare.structuremergeviewer.DiffNode.getName(DiffNode.java:187)
	at org.eclipse.compare.structuremergeviewer.DiffTreeViewer$DiffViewerLabelProvider.getText(DiffTreeViewer.java:88)
	at org.eclipse.jface.viewers.ViewerComparator.getLabel(ViewerComparator.java:145)
	at org.eclipse.jface.viewers.ViewerComparator.compare(ViewerComparator.java:129)
	at org.eclipse.jface.viewers.ViewerComparator$1.compare(ViewerComparator.java:192)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
	at java.util.TimSort.sort(TimSort.java:189)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at org.eclipse.jface.viewers.ViewerComparator.sort(ViewerComparator.java:189)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:640)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2649)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1918)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1925)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1893)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1850)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1836)
	at org.eclipse.jface.viewers.StructuredViewer$7.run(StructuredViewer.java:1500)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1436)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:366)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1397)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1497)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:521)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.refreshAfterDiff(StructureDiffViewer.java:522)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.access$4(StructureDiffViewer.java:516)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$9.run(StructureDiffViewer.java:507)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 48 more
```

**Comment by gavinking** [comment] 2015-03-24 15:41
I have eyeballed the code, and also tested the functionality by hand, and I don't see how this could ever happen now. Closing, since code has changed, and there is anyway not enough information here to reproduce the NPE.

**Closed by gavinking** 2015-03-24 15:41 UTC
Labels: bug
