### ISSUE TITLE
Paste code snippet in Ceylon Explorer package should create a .ceylon file

### ISSUE THREAD

**Issue by PhiLhoSoft** [ceylon/ceylon-ide-eclipse#1225] opened 2015-01-28 13:16 UTC
A trick I appreciate in Eclipse Java is that I can copy a code snippet in a file, then select a package (eg. in the Project Explorer) and paste the snippet. Eclipse will create a .java file with the snippet in it.
If I copied a whole class, the new file will have the class name and a package declaration is added.
Otherwise, it names the file Snippet and creates a class of same name where it pastes the code.

I tried this in the Ceylon Explorer (out of habit), and I got... a Snippet.java file with a Java class declaration!

It would be nice if the Ceylon plugin could detect such action and just create a Snippet.ceylon file with the code pasted raw (or in a class?) in it. Or be a little smarter and detect if we paste a class or interface, to name the file after the (first) found item.

**Comment by gavinking** [comment] 2015-03-21 19:16
I guess what is needed for this one is a customized `CCPActionGroup` at `CeylonNavigatorStandardActionsProvider.java:69`. Probably not super-hard.

**Comment by gavinking** [comment] 2015-03-21 19:36
Yep: it's actually `PasteAction.TextPaster` that does this work for Java.

**Comment by gavinking** [comment] 2015-03-21 21:12
@PhiLhoSoft I have implement this. WDYT?

**Comment by PhiLhoSoft** [comment] 2015-03-22 13:52
Great! Thanks for this. (and for the autocompletion on camel case too).
As soon as it is available in an update (sorry, no time to build the IDE by myself), I will try it and report feedback (or just use it happily if working flawlessly... :smile:).

**Comment by DiegoCoronel** [comment] 2015-03-23 20:05
Hi Gavin, i tried to copy 3 files (the file .ceylon, not the content) to another package and now it opens the popup for the snippet, maybe thats not a intended behavior.

**Comment by gavinking** [comment] 2015-03-23 22:43
@DiegoCoronel hopefully should be fixed now.

**Comment by DiegoCoronel** [comment] 2015-03-24 00:52
checked, thanks,

**Comment by gavinking** [comment] 2015-03-24 15:11
Closing. @PhiLhoSoft can reopen if there's something wrong with it.

**Closed by gavinking** 2015-03-24 15:11 UTC
Labels: feature
