### ISSUE TITLE
Completion prevent typing

### ISSUE THREAD

**Issue by gkutiel** [ceylon/ceylon-ide-eclipse#1806] opened 2016-06-26 23:56 UTC
Can not type while content completion is triggered. To reproduce, set the Auto-activation delay to 1ms and start typing, all the keystrokes while content completion dialog is loading are gone. 

Ubuntu 16.04

Eclipse:
Version: Neon Release (4.6.0)
Build id: 20160613-1800

Ceylon IDE
Version: 1.2.2 ("Charming But Irrational")

**Comment by gavinking** [comment] 2016-09-28 12:18
I can't reproduce this, at least not on Mac with the 1.3.0 release.

@gkutiel would you try updating to the latest release of Ceylon IDE and see if you still experience this? Thanks.

**Comment by gavinking** [comment] 2016-09-28 15:25
Actually, I'm certain this must have been fixed by @davidfestal's recent work on completion. So I'm going to take the liberty of closing this one, and @gkutiel can reopen it if necessary.

**Closed by gavinking** 2016-09-28 15:25 UTC
Labels: bug on last release, proposals/fixes/assists, WAITING_FOR_ANSWER
