### ISSUE TITLE
Adapt to Luna’s dark theme

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1001] opened 2014-06-28 18:07 UTC
The new Eclipse Luna has a dark theme; the following components should detect it and change their colors accordingly:
* editor
* outline
* type hierarchy
* explorer? The expand arrows are hard to spot, but JDT’s package explorer doesn’t change them.

See [`IThemeManager`](http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fui%2Fthemes%2FIThemeManager.html) and perhaps [Eclipse Bug 425646](https://bugs.eclipse.org/bugs/show_bug.cgi?id=425646).

**Comment by gavinking** [comment] 2015-06-16 17:17
I had a look at this today, and after wasting the usual hours on Eclipse's undocumented APIs, my conclusion is that I have no idea if this is doable. There are a couple of different things being called "themes" here, and they don't appear to have anything to do with each other. In particular, it does not appear to be possible to detect the Dark theme via `ITheme` or `IThemeManager`, nor interact with it via `< colorOverride>`s.

**Comment by gavinking** [comment] 2015-06-16 17:18
Perhaps @vogella could give us some advice here?

**Comment by vogella** [comment] 2015-06-16 17:23
+lucaswerkmeister the arrows have been fixed in Eclipse 4.5.

**Comment by vogella** [comment] 2015-06-16 17:25
@gavinking its super easy, we support setting of preferences via CSS. Just a sec, I need to search my info email about this to the Eclipse cross distribution list...

**Comment by vogella** [comment] 2015-06-16 17:28
@gavinking also I strongly recommend to use Eclipse 4.5, because we have hugely improved the support for the default dark theme in this release.

Have fun styling.

**Comment by vogella** [comment] 2015-06-16 21:28
Screenshot of Eclipse 4.5, Scrollbars are the remaining pains, as SWT has no API yet to style them.

![image](https://cloud.githubusercontent.com/assets/139910/8194955/5e86eec0-147f-11e5-97f6-4c1310edd6f8.png)

**Comment by gavinking** [comment] 2015-06-17 09:23
@vogella The problem we have here is that in order to apply a different syntax highlighting color scheme when the dark theme is is selected, I need some way to detect that it is enabled. I can't see any way to do that via the `ITheme` or `IThemeManager`, nor any other obvious way.

The only thing I can think of right now would be to look at the background color of the Ceylon editor and apply a different set of colors if it is black. But that doesn't seem like the right solution.

Any idea? Thanks.

**Comment by vogella** [comment] 2015-06-17 10:22
@gavinking Did you look at my proposed solution? No listener is required if you simply extend the dark theme and set whatever you need to set in via your CSS.

**Comment by lucaswerkmeister** [comment] 2015-06-17 10:28
@vogella so `org.eclipse.e4.ui.css.theme.e4_dark` is the name of the dark theme, and we need to extend it?

**Comment by gavinking** [comment] 2015-06-17 10:39
@vogella I apologize, I didn't see that comment.

But I'm not trying to style widgets, so it seems to me like the CSS approach is a bit too "hardcoded", unless I'm missing something.

Right now we use the Eclipse themes API to register the colors used by the syntax highlighter, i.e.

```xml
   <extension point="org.eclipse.ui.themes">
    <themeElementCategory
        id="com.redhat.ceylon.eclipse.ui.theme" 
        label="Ceylon">
        <description>
            Ceylon editor
        </description>
    </themeElementCategory>
    <colorDefinition
        categoryId="com.redhat.ceylon.eclipse.ui.theme"
        id="com.redhat.ceylon.eclipse.ui.theme.color.keywords" 
        label="Keywords"
        value="76,76,76">
        <description>
            Color for highlighting Ceylon keywords
        </description>
    </colorDefinition>
    ...
```
Thus allowing the user to customize them via General > Appearance > Colors and Fonts. And we look them up using the `ITheme`.

What I'm trying to do is figure out how you could make the syntax highlighting adapt to the dark theme without removing the ability to customize the colors.

**Comment by vogella** [comment] 2015-06-17 11:32
@lucaswerkmeister correct.

@gavinking also possible via CSS. I feel you don't want to here this answer but you can also work with Colors and Fonts via CSS. See http://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.ui.themes/css/e4_basestyle.css for an example and http://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.ui.themes/css/e4-dark.css for its usage.

Key is to register yourself with the default dark theme. I hope I have give sufficient examples to solve that riddle. :-)

**Comment by gavinking** [comment] 2015-06-17 11:36
Ah OK, so the `ColorDefinition#XXXXX` nodes? OK, I guess we can try that.

**Comment by gavinking** [comment] 2015-06-18 00:37
@vogella So I tried adding this to `plugin.xml`:

```xml
    <extension point="org.eclipse.e4.ui.css.swt.theme">
        <stylesheet
              uri="css/light.css">
              <themeid refid="org.eclipse.e4.ui.css.theme.e4_classic"/>
              <themeid refid="org.eclipse.e4.ui.css.theme.e4_default"/>
        </stylesheet>
        <stylesheet
              uri="css/dark.css">
              <themeid refid="org.eclipse.e4.ui.css.theme.e4_dark"/>
        </stylesheet>
    </extension>
```

And then I have, in `dark.css`, the following:

```css
ColorDefinition#com-redhat-ceylon-eclipse-ui-theme-color-keywords {
    color: #b8baaf;
    category: '#com-redhat-ceylon-eclipse-ui-theme';
}
ColorDefinition#com-redhat-ceylon-eclipse-ui-theme-color-identifiers {
    color: #ef6155;
    category: '#com-redhat-ceylon-eclipse-ui-theme';
}
ColorDefinition#com-redhat-ceylon-eclipse-ui-theme-color-types {
    color: #fec418;
    category: '#com-redhat-ceylon-eclipse-ui-theme';
}
ColorDefinition#com-redhat-ceylon-eclipse-ui-theme-color-strings {
    color: #48b685;
    category: '#com-redhat-ceylon-eclipse-ui-theme';
}
```

But these overrides don't seem to be picked up at all.

Naturally, there's zero error reporting of any kind, making it pretty impossible to know what I'm doing wrong. Any ideas?

**Comment by vogella** [comment] 2015-06-18 07:48
IIRC the classes to debug are CSSPropertyThemesExtensionHandler and CSSPropertyColorDefinitionHandler

In the Eclipse platform.ui repo you find under examples org.eclipse.e4.demo.cssbridge which demonstates the usage of ColorDefinition.

git clone git://git.eclipse.org/gitroot/platform/eclipse.platform.ui

**Comment by gavinking** [comment] 2015-06-18 10:18
OK, so it seems that the issue is that I have to add the `org.eclipse.e4.ui.css.swt` module as a dependency in `MANIFEST.MF`, or my color definitions are simply ignored.

**Comment by vogella** [comment] 2015-06-18 10:39
So it works? Nice. Please post screenshot so that I can see your result.

**Comment by gavinking** [comment] 2015-06-18 11:00
@vogella Nope, still doesn't work. The stuff I specify in the CSS file gets immediately overwritten by the defaults from `plugin.xml`, because line 191 of `WorkbenchThemeManager` doesn't take into account CSS-defined colors _at all_.

I really don't see how I'm supposed to use this stuff.

**Comment by gavinking** [comment] 2015-06-18 11:02
i.e. there is a tiny split-second where my css color definitions are in effect, and I even see them in the editor, but then the theme manager immediately throws them away and replaces them with the values defined in `plugin.xml`.

**Comment by vogella** [comment] 2015-06-18 11:04
Can you first try to define your own CSS based theme and select it via via General -> Appearance. Does this work?

**Comment by gavinking** [comment] 2015-06-18 11:06
@vogella well surely that would work but that's simply not an acceptable solution here.

**Comment by gavinking** [comment] 2015-06-18 11:06
Themes are _totally_ orthogonal to Ceylon development. There should not be a Ceylon theme.

**Comment by vogella** [comment] 2015-06-18 11:09
@gavinking just for testing, please try it. Your CSS might have errors and this is good way to test this.

**Comment by gavinking** [comment] 2015-06-18 11:32
@vogella I know my CSS is working. Like I said, I can see the colors in the Ceylon editor. As long as I cache colors before line 191 of `WorkbenchThemeManager` is executed, all is good.

Debugging, I can see the `WorkbenchThemeManager` throw away my CSS-defined colors and replace them with the default values.

**Comment by vogella** [comment] 2015-06-18 11:46
I did not dig into the details but the example I gave you is working. So what is the difference?

**Comment by gavinking** [comment] 2015-06-18 11:50
Well for a start the example is defining a new theme, not trying to contribute something to an existing theme.

**Comment by gavinking** [comment] 2015-06-18 11:52
Oh wait, you mean the EGit example. Let me check.

**Comment by gavinking** [comment] 2015-06-18 11:54
Ohwell, the EGit example doesn't actually override any `colorDefinition`s.

**Comment by vogella** [comment] 2015-06-18 11:55
I think Egit does not use ColorDefinitions. Maybe we still have a bug in the theme engine, I'm not aware of an extender which uses ColorDefinitions.

If that is the case and you provide a fix, I will try to put it into 4.5.1. FYI - I will be soon leaving for vacations, so you won't hear from me in a while.

**Comment by gavinking** [comment] 2015-06-18 11:59
Aaaah I figured it out. So they hack around the bug by messing directly with the preferences.

OK I can do it that way.

**Comment by vogella** [comment] 2015-06-18 12:04
No the only use perferences not color definitions.

Can you open a bug for us, maybe with a tiny example so that we can solve this issue?

**Comment by gavinking** [comment] 2015-06-18 12:44
OK, great, it "works". Thanks so much for your help on this, Lars.

FTR, the complete solution can be seen in commit @075d5e153e801096a1980a8c8d74564e83ec7c74. It's a total hack. You have to mess directly with workbench and editors plugin preferences, even duplicating stuff out of `e4-dark_preferencestyle.css`.

Note that there are huge bugs in this infrastructure, for example, hitting Restore Defaults in the Colors and Fonts preference page will hammer the dark theme settings with the defaults from `plugin.xml`.

**Comment by vogella** [comment] 2015-06-18 12:51
@gavinking pleasure to help. Please open Bugs for Eclipse Platform so that we can solve the issues you identified.

**Comment by gavinking** [comment] 2015-06-18 13:17
The result:

![screen shot 2015-06-18 at 3 13 22 pm](https://cloud.githubusercontent.com/assets/579974/8232048/09ce89fc-15cd-11e5-82cf-cf8a066e2ee7.png)

**Comment by klinger** [comment] 2015-06-28 20:57
Thanks!
With the change today even the not visible parts in ceylon explorer are visible. I am so happy, you finally made the  dark theme usable - have been waiting (and looking at this issue for months). No need to use intellij  anymore.

**Comment by gavinking** [comment] 2015-06-30 22:39
@vogella I still have an intermittent problem here.

_Sometimes_, I don't get any notifications from the `ThemeManager` letting me know about the Dark theme preferences. I register a `IPropertyChangeListener` with the current `Theme`, but _sometimes_ it doesn't get called.

Any idea what is the _correct_ way to listen for changes to the theme in order to be sure we'll be notified when the dark theme CSS is applied?

**Comment by vogella** [comment] 2015-08-03 11:08
If you extend our theme, you do not need to add a preference change listener. If you still want for any reason and it is not called please open a bug with a small reproducable example.

**Comment by klinger** [comment] 2015-08-16 07:59
I only had a minor problem: I had to change the colour of **Keywords** and **Braces**. Their default colour was black. 

Window>Preferences>General>Appearence>Colours and Fonts> Ceylon

My System: Linuxmint, head revision

**Comment by lucaswerkmeister** [comment] 2015-10-03 20:55
> I only had a minor problem: I had to change the colour of Keywords and Braces. Their default colour was black.

I actually like them this way, it’s still readable for me.

There’s one other thing which is irritating, though:
![screenshot from 2015-10-03 22-53-14](https://cloud.githubusercontent.com/assets/2346599/10265080/b90173aa-6a21-11e5-8be3-e1875dd91e25.png)
Highlighted elements and lines are still bright, which can be fairly jarring since it can happen on any click – flash!

**Comment by gavinking** [comment] 2015-10-03 22:38
@klinger that's fixed now&mdash;stupid mistake on my part.

Both Dark/Default and Dark/Ceylon Dark Alt seem to be working for me now.

**Comment by gavinking** [comment] 2015-10-03 22:47
This seems to be working well enough, so I'm finally closing this issue.

**Closed by gavinking** 2015-10-03 22:47 UTC
Labels: editor/hover/outline
