### ISSUE TITLE
Module dropped from Explorer when a Maven dependency is added

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-ide-eclipse#1302] opened 2015-03-23 20:01 UTC
Hi,
When I add:
```ceylon
import "org.hibernate:hibernate-entitymanager" "4.3.8.Final";
```
to a module descriptor, the corresponding module disappears from Ceylon Explorer.
With other artifacts (eg  "com.h2database:h2" "1.4.186") everything is OK.
The Maven artifact is correctly downloaded to ~/.m2.
I'm on Linux 64 bits (Mint), Eclipse Luna, java 1.7.

**Comment by davidfestal** [comment] 2015-03-24 17:30
@jpragey : are you in Hierarchical or flat mode ? I'm asking this to find out whether this is linked to issue #1238, which is for 1.3.
@gavinking : do you think it could be ?

**Comment by jpragey** [comment] 2015-03-24 21:47
I'm in flat mode.
Well, the PB is the same in hierarchical mode.
It's easy to reproduce: create a new project, create a new module, copy/paste the faulty line and the module goes away.

**Comment by davidfestal** [comment] 2015-03-25 10:21
@jpragey : yes,in the meantime, I've been able to reproduce it

**Comment by davidfestal** [comment] 2015-03-25 11:38
@jpragey : well, I don't succeed in reproducing it anymore... Even with a newly-created project and the maven artifact not already existing in the maven local repo.

**Comment by jpragey** [comment] 2015-03-25 13:02
Yes, it's still here, but now I have a message in a  'Problem occurred' dialog box:
```
Errors occurred during the build.
Errors running builder 'Ceylon Builder' on project 'bug1302'.
org.jboss.shrinkwrap.resolver.api.maven.MavenArtifactInfo.isOptional()Z
```
I just tried in a fresh workspace with an empty maven repo.

**Comment by davidfestal** [comment] 2015-03-25 13:05
this one seems to be quite new. I've had this new error also recently, but didn't find out the reason for now.

**Comment by jpragey** [comment] 2015-03-25 13:39
If that can help , the whole workspace is at:
https://drive.google.com/file/d/0B09FzhUz_CgbZmhURDZlT1NfcjA/view

**Comment by davidfestal** [comment] 2015-03-25 15:49
@jpragey : though I didn't succeed in reproducing the problem as you encountered it, this commit might have fixed it : 5acdb25f42a175a7148b00373c1c58de2cff951b
Can you pull and check again ?

**Comment by jpragey** [comment] 2015-03-25 16:21
Unfortunately it's still alive...

**Comment by jpragey** [comment] 2015-03-25 18:59
Well, after a full Eclipse reinstall, I couldn't reproduce this bug either. So I'm OK to close it.

**Comment by davidfestal** [comment] 2015-03-25 20:47
OK,closing then.

**Closed by davidfestal** 2015-03-25 20:47 UTC
Labels: bug, COULD_NOT_REPRODUCE_ANYMORE, WAITING_FOR_ANSWER
