### ISSUE TITLE
Running ceylon.net tests

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1400] opened 2015-07-09 09:40 UTC
If I try to run the ceylon.net tests (i.e. the module `test.ceylon.net` as a Ceylon Test) in the IDE I get the following error:

ceylon test: Error while loading the test.ceylon.net/1.1.1 module:
 Declaration 'java.net.URI' could not be found in module 'test.ceylon.net' or
its imported modules but was found in the non-imported module 'java.base'
com.redhat.ceylon.model.loader.ModelResolutionException: Error while loading the test.ceylon.net/1.1.1 module:
 Declaration 'java.net.URI' could not be found in module 'test.ceylon.net' or its imported modules but was found in the non-imported module 'java.base'
	at com.redhat.ceylon.compiler.java.runtime.model.RuntimeModelLoader$1.reportError(RuntimeModelLoader.java:209)
	at com.redhat.ceylon.model.typechecker.model.UnknownType.reportErrors(UnknownType.java:94)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getMetamodel(Metamodel.java:504)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeValue.<init>(FreeValue.java:43)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeReference.<init>(FreeReference.java:17)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getOrCreateMetamodel(Metamodel.java:344)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.init(FreeClassOrInterface.java:92)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClass.init(FreeClass.java:51)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.checkInit(FreeClassOrInterface.java:144)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.filteredMembers(FreeClassOrInterface.java:212)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.annotatedMemberDeclarations(FreeClassOrInterface.java:186)
	at ceylon.test.core.findCandidatesInClass_.findCandidatesInClass(DefaultTestRunner.ceylon:206)
	at ceylon.test.core.findCandidatesInPackage_.findCandidatesInPackage(DefaultTestRunner.ceylon:200)
	at ceylon.test.core.findCandidatesInModule_.findCandidatesInModule(DefaultTestRunner.ceylon:191)
	at ceylon.test.core.findCandidatesInModuleLiteral_.findCandidatesInModuleLiteral(DefaultTestRunner.ceylon:259)
	at ceylon.test.core.findCandidatesInTypeLiteral_.findCandidatesInTypeLiteral(DefaultTestRunner.ceylon:233)
	at ceylon.test.core.findCandidates_.findCandidates(DefaultTestRunner.ceylon:183)
	at ceylon.test.core.createExecutors_.createExecutors(DefaultTestRunner.ceylon:85)
	at ceylon.test.core.DefaultTestRunner.initExecutors$priv$(DefaultTestRunner.ceylon:43)
	at ceylon.test.core.DefaultTestRunner.<init>(DefaultTestRunner.ceylon:46)
	at ceylon.test.createTestRunner_.createTestRunner(TestRunner.ceylon:49)
	at ceylon.test.createTestRunner_.createTestRunner(TestRunner.ceylon:48)
	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:85)
	at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:36)
	at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:246)
	at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:173)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)

The thing is that the `test.ceylon.net` module.ceylon does `import java.base "7";` The tests run fine in the CLI.

**Comment by davidfestal** [comment] 2015-07-16 14:36
The JDT model loader doesn't seem involved. I din't see how it is related to the IDE.

**Comment by davidfestal** [comment] 2015-08-04 12:03
@tombentley , @FroMage, @quintesse, it's not  IDE-specific or JDTModelLoder-specific : I get a similar errors when running the `ceylon test` ant wrapper on the command line on the IDE Ceylon project.

**Comment by davidfestal** [comment] 2015-08-04 12:06
@thradec : it seems to me that, when searching for candidates, if `ceylon test` encounters this error, it should simply ignore it : it means that the corresponding declaration is not visible in this context (has not been publicly imported). Am I wrong ?

**Comment by quintesse** [comment] 2015-08-04 12:22
@davidfestal  I didn't test in the IDE but on the command line I don't see that error, not running `ant test`, nor running `ceylon test test.ceylon.net` directly.

**Comment by davidfestal** [comment] 2015-08-04 12:31
@quintesse : yes, apparently when it fails with `java.base`-related classes, the error doesn't happen on the command line.
But if you try to run the tests on the IDE ceylon project, with `ant test` from the command-line, you will get the same type of errors, but this time with the `IEditor` class (which is an eclipse API class) : 

```
test:
[ceylon-test] ceylon test: Error while loading the com.redhat.ceylon.eclipse/1.1.1 module:
[ceylon-test]  Declaration 'org.eclipse.ui.IEditorPart' could not be found in module 'com.
[ceylon-test] redhat.ceylon.eclipse' or its imported modules but was found in the non-
[ceylon-test] imported module 'org.eclipse.ui.workbench'
[ceylon-test] com.redhat.ceylon.model.loader.ModelResolutionException: Error while loading the com.redhat.ceylon.eclipse/1.1.1 module:
[ceylon-test]  Declaration 'org.eclipse.ui.IEditorPart' could not be found in module 'com.redhat.ceylon.eclipse' or its imported modules but was found in the non-imported module 'org.eclipse.ui.workbench'
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.model.RuntimeModelLoader$1.reportError(RuntimeModelLoader.java:209)
[ceylon-test] 	at com.redhat.ceylon.model.typechecker.model.UnknownType.reportErrors(UnknownType.java:94)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getMetamodel(Metamodel.java:504)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeValue.<init>(FreeValue.java:43)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeReference.<init>(FreeReference.java:17)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getOrCreateMetamodel(Metamodel.java:344)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FunctionalUtil.getParameters(FunctionalUtil.java:22)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.<init>(FreeFunction.java:60)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getOrCreateMetamodel(Metamodel.java:341)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.init(FreeClassOrInterface.java:92)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClass.init(FreeClass.java:51)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.checkInit(FreeClassOrInterface.java:144)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.filteredMembers(FreeClassOrInterface.java:212)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.annotatedMemberDeclarations(FreeClassOrInterface.java:186)
[ceylon-test] 	at ceylon.test.core.findCandidatesInClass_.findCandidatesInClass(DefaultTestRunner.ceylon:206)
```

It seems that the `java.base` case is a bit a special case : I assume it works on the CLI because of a specific condition that probably makes `java.base` classes accessible from everywhere (since it's the JVM backend). And this condition is probably not met when run inside the IDE.

**Comment by quintesse** [comment] 2015-08-04 12:41
@davidfestal I don't know, the original error @tombentley reported says:

    Declaration 'java.net.URI' could not be found in module 'test.ceylon.net' or its imported modules but was found in the non-imported module 'java.base'

But `test.ceylon.net` **does** import `java.base`! So to me that suggests something is not right there in the IDE as Tom suspected.

**Comment by davidfestal** [comment] 2015-08-04 12:52
@quintesse : strange indeed.

**Comment by thradec** [comment] 2015-09-04 13:06
I was able to reproduce this bug, when the `test.ceylon.net-1.1.1.car` was produced by eclipse, which run under java 8 (in that case it fails from IDE and from CLI too), with java 7 it works fine from both places.

I decompiled the non-functioning archive and in `$module_.class` found this
`@com.redhat.ceylon.compiler.java.metadata.Import(name="java.base", version="8")`.

**Comment by davidfestal** [comment] 2015-09-25 09:59
Indeed the problem in the IDE is that, despite the change made in fixing issue ceylon/ceylon-compiler#1882, the CeylonIDE build still turns `java.base 7` dependencies into `java.base 8` as soon as Eclipse is running under Java 8.

This is related to the fact that the Eclipse plugin Ceylon build *reuses* the typechecker model. And in the IDE typechecker model lifecycle, the JDK modules are loaded inside the `ModuleManager` (with `loadStandardModules()`) *before* the source module descriptor visit (with `PhasedUnit.visitRemainingModulePhase()`). 

Since `AbstractTransformer.makeAtModule()` uses the `Module` object model of the `ModuleImport` model object, the code is generated with version 8 in our case.

Indeed, to retrieve the module import version, `makeAtModule()` should have a look in the module descriptor AST, and *not* only in the imported `Module` object (at least for JDK module imports)

I'm currently making this change in the `AbstractTransformer`

**Comment by davidfestal** [comment] 2015-09-25 10:24
So now the IDE Ceylon build doesn't generate v8 imports for original v7 imports anymore.

@tombentley, @thradec : do you confirm that this also fixes the original issue ?

**Comment by gavinking** [comment] 2015-10-06 10:28
I just ran the `ceylon.net` tests on Java 8 and it looks like this fix is good. Closing.

**Closed by gavinking** 2015-10-06 10:28 UTC
Labels: bug, launch/run/debug, test plugin, WAITING_FOR_ANSWER
