### ISSUE TITLE
"Setting up typechecker" phase hangs and can't be cancelled 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1517] opened 2015-10-03 23:33 UTC
OK, this is just incredibly painful. If the "Setting up typechecker" job hangs while trying to retrieve a dependency:

- the build it can't be canceled,
- the job holds a hard lock on the whole project

What this means is that I have to stop the whole process to recover from this. 

This is especially bad b/c recently I've been getting hands pretty regularly here. We need to fix it.

**Comment by gavinking** [comment] 2015-10-03 23:38
I mean the freaking thing hangs while "resolving module ceylon.language/1.1.1" and can't be cancelled. What a mess.

**Comment by gavinking** [comment] 2015-10-04 00:00
Yeah, great, so I have a workspace that is out of date with the FS. And every time I try to Refresh, the resulting build hangs at "resolving module ceylon.language/1.1.1" and I have to restart Eclipse. Awesome.

**Comment by gavinking** [comment] 2015-10-04 01:04
FTR: I resolved this by disabling the backends, which eliminated the hang.

**Comment by davidfestal** [comment] 2015-10-06 19:37
would you have a stacktrace or something like that ? Or a thread dump of the when the `Settings Typechecker` phase was hanging on the language module, or at least steps to reproduce the issue ?

**Comment by davidfestal** [comment] 2015-10-07 12:42
@gavinking : I've been looking into the code but don't see anything obvious that might produce this issue.
Do you have any way to reproduce it ?

**Comment by gavinking** [comment] 2015-10-07 16:12
1. Open the `ceylon-sdk` project in the IDE
2. Enable back backends
3. from the commandline, checkout some different snapshot of the `ceylon-sdk` project
4. Make sure both backends are enabled in `.project`
5. Refresh `ceylon-sdk`.

**Comment by davidfestal** [comment] 2015-10-08 09:56
so it seems it's not deadlocked, but the `JDTModelLoader` is waiting for the current Java indexing Job to stop. And in fact the binary generation by the Java backend triggers the Java indexing (of class files changed in the `.exploded` directory). And in this case there is a huge amount of classes to index.

I'll have a look to enable the cancellation of this.

**Comment by davidfestal** [comment] 2015-10-08 11:29
And this happen because, when resolving a module from binaries, the `JDTModuleLoader` is used to load the module descriptor from binaries, and in turns, JDT tries to load the `package-info.class` of the related package. Since the `package-info` class is not found (because it doesn't exist of course), the model loader looks for it by requesting a search including the secondary types. And searching for the secondary types requires waiting for the end of the current Java indexing jobs.

Here is the solution :
- don't search for secondary types when the searched class is a `package-info` class. This should avoid the "resolving module ..." job to be blocked by the current indexing  systematically.
- Allow cancelling of the secondary types search when the enclosing build-related job has been cancelled.

**Closed** 2015-10-08 16:05 UTC
Labels: bug, high priority

**Comment by gavinking** [comment] 2015-10-08 16:08
Thankyou David!
