### ISSUE TITLE
console exceptions and tests link to wrong source file

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1678] opened 2016-01-22 16:08 UTC
Clicking on a file & line number in the console (or a test in the test view) can take you to a source file of the same name and package in the wrong project.

I believe this started happening for me with 1.2.0 SR1.

To reproduce:

1. Create a new workspace (or don't)
2. Create a new project, module, and source file: `Project1/source/simple/run.ceylon` with contents as shown below
3. Create a second project with `Project2/source/simple/run.ceylon`
4. Run *Project2*'s `run2` top-level function.
5. Click on `at simple.run2_.run2(run.ceylon:3)` in the console. This takes you to *Project1*'s `run.ceylon` file.

Project 1's `run.ceylon`:
```ceylon
// Project 1
shared void run1() {
    throw Exception("Project1");
}
```

Project 2's `run.ceylon`
```ceylon
// Project 2
shared void run2() {
    throw Exception("Project2");
}
```

**Comment by thradec** [comment] 2016-01-22 16:11
closing, duplicate of #1435

**Closed by thradec** 2016-01-22 16:11 UTC

**Comment by jvasileff** [comment] 2016-01-22 16:13
Oops, thanks!
