### ISSUE TITLE
Compilation error when using `Boolean isNative()` vs `String getNative()`

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1369] opened 2015-06-05 16:02 UTC
The following code builds fine in the IDE:

```
import com.redhat.ceylon.model.typechecker.model {
    Declaration
}

shared void ugh(Declaration decl) {
    if (exists nat = decl.native) { 
        print("yay");
    }
}
```

However it produces a compilation error in the CLI:

> source/org/intellij/plugins/ceylon/ide/ceylonCode/doc/docUtils.ceylon:72: error: expression must be of optional type: 'Boolean' is not optional
>    if (exists nat = decl.native) {

Changing `exists nat = decl.native` to `decl.native` works in the CLI but not in the IDE:

> Expression must be of boolean type: String is not assignable to Boolean

**Comment by gavinking** [comment] 2015-06-05 16:05
One for you @davidfestal.

**Comment by quintesse** [comment] 2015-06-05 18:33
I didn't really think about the usability of the API in Ceylon when I added `getNative()`, should we change the name?

**Comment by gavinking** [comment] 2015-06-05 18:43
Yes.

**Comment by davidfestal** [comment] 2015-06-05 18:52
why not `getNativeBackend()` ?

**Comment by davidfestal** [comment] 2015-06-05 18:56
@quintesse, @FroMage  : which one should have the priority in such a case to be selected for the attribute ? `getNative()` or `isNative()` ? Don't you think that in such a case we should keep both getters and the possible setter as *functions* and *not* produce an attribute in the Ceylon model ?

According to the answer we give to this question the issue is on the IDE or CLI side !

**Comment by bjansen** [comment] 2015-06-05 19:13
Actually I have the exact same problem in `com.redhat.ceylon.model.typechecker.model.TypeDeclaration` with `isSelfType()` and `getSelfType()`...

**Comment by quintesse** [comment] 2015-06-06 08:22
Not entirely sure what would be the best solution, but my first idea would be to have no "preferences" and just leave the java names intact in cases like these.

**Comment by davidfestal** [comment] 2015-06-09 12:42
@quintesse : then I assume it's more a `ceylon-compiler` (more precisely an `AbstractModelLoader`) issue ?
By the way I think that the difference between CLI and IDE here can be explained by the fact that the respective class mirrors return the methods in a different order.

**Comment by quintesse** [comment] 2015-06-09 16:52
Yes, you should probably move this to `ceylon-compiler`

**Comment by davidfestal** [comment] 2015-06-30 07:52
moved to `ceylon-compiler`

**Comment by davidfestal** [comment] 2015-08-14 14:53
closing since the compiler issue is now closed

**Closed by davidfestal** 2015-08-14 14:53 UTC
Labels: bug, high priority
